# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApi' do
pod 'Alamofire'


  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApi

  target 'DemoApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoApiUITests' do
    # Pods for testing
  end

end
